import Head from 'next/head';
import {Inter} from '@next/font/google';
import HomePage from "@/pages/HomePage";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>دیان همراه فردا</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/images/Logos/DianHamrah.jpg"/>
            </Head>
            <main className="main bg-sky-50">
                <HomePage/>
            </main>
        </>
    )
}
